### ISSUE TITLE
[Bug]:  0.118.0 No cursor when using black text on white background (regression: worked in 0.117.0)

### ISSUE THREAD

**Issue by Jamie-Landeg-Jones** [termux/termux-app#2653]
### Problem description

Whilst it was fine in 0.117.0, the cursor is no longer visible with 0.118.0 when using a black text on white background theme.

### Steps to reproduce the behavior.

install 0.118.0 and set the foreground and background colours appropriately, or install one of the black on white themes

### What is the expected behavior?

A visible cursor!

### System information

* Termux application version: 0.118.0
* Android OS version: 9
* Device model: Chromebox Reference

**Comment by Jamie-Landeg-Jones** [comment]
I was just using black background colour and white foreground in colors.properties but the same thing happens with any white foreground, for instance, the "black on white" style.

https://user-images.githubusercontent.com/483894/157988092-6debd73f-9f37-445f-8d71-7cea04a7508f.mp4


Attached is a quick demonstration - at the end i'm pressing cursor-left - you can see how the text on the command line
responds

I just had a further look around, and this looks suspect: https://github.com/termux/termux-app/pull/2228/commits/4a74618f17a65bcafba67b7bf85273390dfa64cb

I tried adding this to colors.properties but it didn't do anything:
 was just using black background colour and white foreground in colors.properties but the same thing happens with any white foreground, for instance, the "black on white" style.

Attached is a quick demonstration - at the end i'm pressing cursor-left - you can see how the text on the command line
responds

I just had a further look around, and this looks suspect: https://github.com/termux/termux-app/pull/2228/commits/4a74618f17a65bcafba67b7bf85273390dfa64cb

I tried adding this to colors.properties but it didn't do anything:

cursor: #ffa9aaa9

I can't compile the source at the moment, so I wasn't able to try regressing the above patch.

It woould seem to be useful if the default cursor colour was dark when the background colour is close to white. Or maybe an option to set the cursor [colour?]

Let me know if you need anything else.

Thanks, Jamie
cursor: #ffa9aaa9

I can't compile the source at the moment, so I wasn't able to try regressing the above patch.

It woould seem to be useful if the default cursor colour was dark when the background colour is close to white. Or maybe an option to set the cursor [colour?]

Let me know if you need anything else.

Thanks, Jamie

**Comment by agnostic-apollo** [comment]
> cursor: #ffA9AAA9

You need to add `cursor: #000000` to `~/.termux/color.properties` after selecting `Black on White` theme. Then restart termux or run `termux-reload-settings`.

> I just had a further look around, and this looks suspect: 4a74618

Yeah, previously default color was grey and was changed to white with the commit cause its easier to read text with white as contrast. However, issue is not with the commit, but with the color themes. "Some" don't have `cursor` key set and were relying on termux default value grey. Anyways, I'll look into fixing the termux-provided themes when I merge `termux-styling` with `termux-app` soon.

The default color will not be changed though since if you are using custom theme, then it's your responsibility to set colors appropriately. There should ideally have been a wiki for it.

> Apologies for the edits, my browser went mental and I had to force-close it)

Yeah, yeah, blame the poor browser...

**Comment by dessalines** [comment]
When using android dark mode, the cursor color in color.properties is completely ignored, and is alway black.

**Comment by agnostic-apollo** [comment]
> When using android dark mode, the cursor color in color.properties is completely ignored, and is alway black.

It's working fine on my android 11. Dark mode with `cursor=#ffffff` sets a white cursor. As far as I see, night mode should not affect terminal colors and only other components like left drawer, etc.

What's your termux app version?

Post `color.properties` and screenshots/video.

**Comment by dessalines** [comment]
Yep just verified again, this is only an issue when using android dark mode, it ignores the cursor color.

```
termux-info
Application version:
0.118.0
Packages CPU architecture:
aarch64
Subscribed repositories:
# sources.list
deb https://termux.mentality.rip/termux-main stable main
Updatable packages:
apt/stable 2.4.1 aarch64 [upgradable from: 2.3.15-1]
command-not-found/stable 1.74 aarch64 [upgradable from: 1.73]
curl/stable 7.82.0 aarch64 [upgradable from: 7.81.0-2]
dialog/stable 1.3-20220117-0 aarch64 [upgradable from: 1.3-20211214-0]
libcurl/stable 7.82.0 aarch64 [upgradable from: 7.81.0-2]
libexpat/stable 2.4.7 aarch64 [upgradable from: 2.4.6]
starship/stable 1.4.2 aarch64 [upgradable from: 1.3.0-2]
termux-tools/stable 0.167 all [upgradable from: 0.166]
Android version:
11
Kernel build information:
Linux localhost 4.14.180-perf-g6231c11929a2 #1 SMP PREEMPT Mon Jan 17 03:17:34 CST 2022 aarch64 Android
Device manufacturer:
Xiaomi
Device model:
21051182G
```

**Comment by agnostic-apollo** [comment]
So actual file name is `colors.properties`, not `color.properties`. Even I miswrote above. Can you try adding it to `~/.termux/colors.properties`? That could be the issue.

**Comment by dessalines** [comment]
You'll notice the cursor is black, yet the code is #ffffff. As soon as I switch to light mode, it correctly is able to change the cursor color.

![IMG_20220312_155531](https://user-images.githubusercontent.com/930215/158034692-71001788-409a-4841-812b-48d25499d247.jpg)

**Comment by agnostic-apollo** [comment]
hmmm, I even installed github `0.118.0` release apk in case any later commits changed the behaviour, but worked fine even with it.

I'll test with android avd later and report back, could be a device specific issue. Are you using f-droid or github builds in case debugging is required?

Was it broken on older releases as well or `0.118.0` broke it? There were theming changes done in the release, although terminal cursor color setting is separate and manually done.

**Comment by dessalines** [comment]
f-droid builds. I don't know if it worked or was broken previously, as this is the only version of termux I've used.

**Comment by Nerd00F** [comment]
@Jamie-Landeg-Jones so, the problem is solved?

**Comment by Jamie-Landeg-Jones** [comment]
> @Jamie-Landeg-Jones so, the problem is solved?

Apologies for the delay - I missed the notification for this.

It's "solved' for me, in that I could manually change the cursor color after I realised I messed up my original attempt.

The other issues reported in this thread are presumably still present.

I don't know the intricacies of the code, so this may be dumb, but I did suggest that if no cursor color is specified, default it to black for light backgrounds, white otherwise.  Brightness can be calculated using something like.


 c.R * c.R * .241 + 
      c.G * c.G * .691 + 
      c.B * c.B * .068

(from  https://www.nbdtech.com/Blog/archive/2008/04/27/Calculating-the-Perceived-Brightness-of-a-Color.aspx )

**Comment by Nerd00F** [comment]
@agnostic-apollo i think you can close this issue

**Comment by agnostic-apollo** [comment]
>I did suggest that if no cursor color is specified, default it to black for light backgrounds, white otherwise. Brightness can be calculated using something like.

@Jamie-Landeg-Jones thanks for the math! I have added your request and seems to be working good with different backgrounds. You can test yourself if using github builds.

https://github.com/termux/termux-app/actions/runs/2509680073

https://github.com/termux/termux-app#Installation

>gulp me and my big mouth!

Too late now, time to pay up! ;)

> "my dog ate my browser"

That's not how you are supposed to bury your browser history!

> slips off embarrassedly

Me at @termux does not let people get away that easily. You stay right here.

**Comment by agnostic-apollo** [comment]
@dessalines Sorry dude, I tried again and can't reproduce it. A video would be helpful, you can also send me privately at agnosticapollo@gmail.com

Does it happen outside text editors too?

Best way to debug this would be with logs. I can add them to the app and you can install and send them back. But you would need to use github builds. Since you installed from F-Droid, you would have to uninstall it first due to different signing keys of F-Droid and github builds, optionally after backing up. Let me know if you are willing to do that.

https://github.com/termux/termux-app#Installation

https://wiki.termux.com/wiki/Backing_up_Termux

**Comment by agnostic-apollo** [comment]
If reinstalling from github, use the build at https://github.com/termux/termux-app/actions/runs/2518728695 instead, it has an unrelated bug fix for bootstrap not being installed.

**Comment by dessalines** [comment]
I reinstalled and it appeared to fix the issue.

**Comment by agnostic-apollo** [comment]
Great. Thanks.
